language: node_js
node_js:
- 8.10.0
install:
- npm install --dev
script:
- npm run build:ssr
- npm run webpack:server
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master