language: node_js
node_js:
  - "8.10.0"
install:
  - npm install --dev
script:
  - npm run build:ssr
  - npm run webpack:server
deploy:
  provider: openshift
  user: 
    secure: "BbYKVqA1FJtq8gtPlXq11j80Jp7/RGhXE8YyYi7GPQC+bo0IWyMeEXwMRhyc+YYgk7m5udjqHxU6ZCMC7Haple23DDt4IEtHx/Up8ox6A1qU7YF3k/D1pbBnPCQ1Bp0rfUzOD7ZG5YK/3kNJm556KmYMG0SDaa/V3UHh5ek/zDWIy5a9o5t1U8Kvqm9plDdrKa6EzYMmwfE4WPivWE66FiHe0ZwPPcL+dCdSerN2IWCnshgr05UptL6brkzV97SzU1iHaTbxvuprFDSuI0mnY7EBvi+9gQJ88ThdMWt+m5qhaHHwgiH5lRiZFLsYp2iWNPuwMDW/gLn1iJPsdmbjF80KWYoaZaaA88AyRbVKwRmPbeoIpJWYVjCatTvXKL+JlidFY3BxIq53jt7xpjs2Wkonvn0JKD/o4FN4SJqyiIsie9bwzL4ZEzLos6g0mZrpslDwhsXQOPddnXt8NYYmtpB9uw9e4qyz3jFhMchrp0W8uicjyohUBSx+jcI9DuDMOEoyENR21+rDPGAkoL126AB8KFhdZTnRdcYcbjfHrfQ0i1Ynx+PXDAMPngvFSEwdX9nPIP2crjHcdSue9XfHJJPX5HiH7GSVmv9DxTsj3xHe0IwuTLZoIw9c3FBZnAwpR2PRRLhz0/kNVqYlKd0mq53bM2ITanAOkYPsK/BJKqQ="
  password:
    secure: "lWHTGiNTtkC6NTx7rXHdvwMciJc6YZ4/m8EgBsyzYHCWcmxl7CWNxvi/AQfXWAPEflo5HOXY6qBR54N0/EJzQPH0yxD2NJc0mEUzaLZeZpLOAP3DbvhoWWf/70yR4UESJ7Omem4CESBnlWuEGBalW3c8BYe+C+lGijUtxJKfpE4njTsRhWcRihmst6EcjFRKXH5JQqutKPUXAE/lOV/33nZKrDNug83BIMxX0t09OW7fykwbcTvcKwU9hu+oP98szdfUK352F39xEHjW0/0I8e9pNNpxX5LXNGPy2l8J0tmPt9Dpp6+4ZrCtmbw0EaPoBGNdbAjG61FL2HSnezjM2wIIfcLUfJASF22n+WvgqOfWJbyNE9pwSlvRJrQTl2Z6ar1IPEO1eO6o3TxF49+NDAVLih7DMqr3S8LsDaA5jnhhRywhFB2OuLS5HlQDhTggaUkr/6MqIoDfW1fREbsWlMfUbSZgRiFnv4IMs63XULBtmMzJQtCHgRuuOdpTx3t+JkUbLO6znXpY5crufRceQq70cW38/XnqNK4yuyRfaZ0W7ytcamR4qZ/yzy2my4PqVefuf6LTm292kIdxW7mZKqsajU9rygBS6lCnzjiaQWayhVp5aSwzo4Dph0Sb7wt6+XEHNuM3rTAnNmquiN3JDGa1lVW22brEaFIv/2HTgnQ="
  domain: starter-us-west-1
  deployment_branch: master
  app: pavel-pleshko