FROM node:8
RUN mkdir /app
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

RUN npm run build:ssr

WORKDIR /app/dist
COPY browser server /app/server/dist

WORKDIR /app
RUN npm run webpack:server

EXPOSE 8080
ENV PORT 8080
ENV CLIENT_EMAIL portfolio.notifier.robot@yandex.ru
ENV EMAIL_TO pavelpleshko92@mail.ru
ENV CLIENT_PASSWORD majapav3983
CMD ["npm","run","serve:ssr"]